apiVersion: apps/v1
kind: Deployment
metadata:
  name: oktouly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oktouly
  template:
    metadata:
      labels:
        app: oktouly
    spec:
      containers:
      - image: okteto.dev/oktouly:latest
        name: oktouly
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "2436212a-8629-448c-bfe3-84f427bfdb46"
        - name: Vless_Path
          value: "/2436212a-8629-448c-bfe3-84f427bfdb46-vl"
        - name: Vmess_UUID
          value: "2436212a-8629-448c-bfe3-84f427bfdb46"
        - name: Vmess_Path
          value: "/2436212a-8629-448c-bfe3-84f427bfdb46-vm"
        - name: Share_Path
          value: "/v2linyyyk"
